### PR TITLE
Modernize demos code to ES6

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by gauntface** [comment]
Sorry but I purposefully didn't do this to make sure it was accessible to everyone (i.e. developers who aren't comfortable with es2015).

**Comment by FluorescentHallucinogen** [comment]
> I purposefully didn't do this

But you did. Just check your current code: it contains const and let variables, arrow functions and promises, that are all not a part of ES5.

**Comment by FluorescentHallucinogen** [comment]
@gauntface 

Currently the source code contains a mixed ES5+ES6 syntax. What about to convert it completely into ES6 or ES5(+promises)?

> to make sure it was accessible to everyone (i.e. developers who aren't comfortable with es2015).

ES6 has more clear syntax and many benefits. The only thing to worry about is ES6 support by older browsers, because ES6 to ES5 transpilation is not used in this project. But looks like all browsers that have Web Push support have ES6 support.

**Comment by gauntface** [comment]
Raised here: https://github.com/gauntface/web-push-book/issues/64

I would like to tackle this myself to ensure I have linting rules to enforce the final decision.

**Pull request closed without merging**
